### ISSUE TITLE
非刚性对齐时产生大量badcase

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [crissallan/Deformation-Transfer-for-Triangle-Meshes#1]
非常棒的项目，我之前也做过相同的事情，但非刚性对齐的效果没你的demo好

但我拿之前的数据来测试时发现产生了很多badcase，和你使用的数据不同的是我的source是低模，target是高模，下面是效果
source：
![image](https://user-images.githubusercontent.com/30692249/114063602-611cea00-98cb-11eb-9a58-3b79c0bd9d73.png)
target：
![image](https://user-images.githubusercontent.com/30692249/114063663-709c3300-98cb-11eb-9df4-e82b377bd416.png)
result：
![image](https://user-images.githubusercontent.com/30692249/114063726-7db92200-98cb-11eb-9f69-ad375d50e839.png)
关键点:
![image](https://user-images.githubusercontent.com/30692249/114063836-9b868700-98cb-11eb-9e38-3b6d6dd28ce9.png)
问题应该不在关键点标注上，我之前拿它们做过实验，你觉得会是什么问题呢

**Comment by crissallan** [comment]
如果可以的话，可以给我一份你的数据吗，我到时候测试一下看看。

**Comment by crissallan** [comment]
> 非常棒的项目，我之前也做过相同的事情，但非刚性对齐的效果没你的demo好
> 
> 
> 
> 但我拿之前的数据来测试时发现产生了很多badcase，和你使用的数据不同的是我的source是低模，target是高模，下面是效果
> 
> source：
> 
> ![image](https://user-images.githubusercontent.com/30692249/114063602-611cea00-98cb-11eb-9a58-3b79c0bd9d73.png)
> 
> target：
> 
> ![image](https://user-images.githubusercontent.com/30692249/114063663-709c3300-98cb-11eb-9df4-e82b377bd416.png)
> 
> result：
> 
> ![image](https://user-images.githubusercontent.com/30692249/114063726-7db92200-98cb-11eb-9f69-ad375d50e839.png)
> 
> 关键点:
> 
> ![image](https://user-images.githubusercontent.com/30692249/114063836-9b868700-98cb-11eb-9e38-3b6d6dd28ce9.png)
> 
> 问题应该不在关键点标注上，我之前拿它们做过实验，你觉得会是什么问题呢
> 
> 

1.可以检查一下是否source和target的关键点一一对应。
2.关键点的顶点序号是从0开始的。

**Comment by ZHANG-SHI-CHANG** [comment]
> > 非常棒的项目，我之前也做过相同的事情，但非刚性对齐的效果没你的demo好
> > 但我拿之前的数据来测试时发现产生了很多badcase，和你使用的数据不同的是我的source是低模，target是高模，下面是效果
> > source：
> > ![image](https://user-images.githubusercontent.com/30692249/114063602-611cea00-98cb-11eb-9a58-3b79c0bd9d73.png)
> > target：
> > ![image](https://user-images.githubusercontent.com/30692249/114063663-709c3300-98cb-11eb-9df4-e82b377bd416.png)
> > result：
> > ![image](https://user-images.githubusercontent.com/30692249/114063726-7db92200-98cb-11eb-9f69-ad375d50e839.png)
> > 关键点:
> > ![image](https://user-images.githubusercontent.com/30692249/114063836-9b868700-98cb-11eb-9e38-3b6d6dd28ce9.png)
> > 问题应该不在关键点标注上，我之前拿它们做过实验，你觉得会是什么问题呢
> 
> 1.可以检查一下是否source和target的关键点一一对应。
> 2.关键点的顶点序号是从0开始的。
> 3.可以一开始选择数量少一点的关键点测试。
> 4.还有一个可以测试的点是：可以用高模去变形得到低模，non-rigid registration只是为了寻找correspondence，所以其实并没有source和target之分。

看了下你的代码，大概找到问题了，你没有对source和target做归一化和刚性对齐，当两者的坐标系差别比较大时会出现问题，我加上这两步效果变好啦，但边缘也有一些曲翘的问题，有时间我再调一下

**Comment by crissallan** [comment]
> > > 非常棒的项目，我之前也做过相同的事情，但非刚性对齐的效果没你的demo好
> > > 但我拿之前的数据来测试时发现产生了很多badcase，和你使用的数据不同的是我的source是低模，target是高模，下面是效果
> > > source：
> > > ![image](https://user-images.githubusercontent.com/30692249/114063602-611cea00-98cb-11eb-9a58-3b79c0bd9d73.png)
> > > target：
> > > ![image](https://user-images.githubusercontent.com/30692249/114063663-709c3300-98cb-11eb-9df4-e82b377bd416.png)
> > > result：
> > > ![image](https://user-images.githubusercontent.com/30692249/114063726-7db92200-98cb-11eb-9f69-ad375d50e839.png)
> > > 关键点:
> > > ![image](https://user-images.githubusercontent.com/30692249/114063836-9b868700-98cb-11eb-9e38-3b6d6dd28ce9.png)
> > > 问题应该不在关键点标注上，我之前拿它们做过实验，你觉得会是什么问题呢
> > 
> > 
> > 1.可以检查一下是否source和target的关键点一一对应。
> > 2.关键点的顶点序号是从0开始的。
> > 3.可以一开始选择数量少一点的关键点测试。
> > 4.还有一个可以测试的点是：可以用高模去变形得到低模，non-rigid registration只是为了寻找correspondence，所以其实并没有source和target之分。
> 
> 看了下你的代码，大概找到问题了，你没有对source和target做归一化和刚性对齐，当两者的坐标系差别比较大时会出现问题，我加上这两步效果变好啦，但边缘也有一些曲翘的问题，有时间我再调一下

好的，感谢指正以及帮忙发掘问题，后续会将此功能补齐。
